[package]
name = "valence_event"
version.workspace = true
edition.workspace = true

[dependencies]
valence_core.workspace = true
valence_packet.workspace = true
bevy_ecs.workspace = true
bevy_app.workspace = true
bitfield-struct.workspace = true


